zap:
  level: debug
system:
  port: 2379
  job-log: "/Users/pengweiquan/pwq/pnsql-fusion/pnsql-task/log"
  #  路由全局前缀
  router-prefix: ""
mysql:
  host: "8.153.100.186"
  port: "3306"
  dbname: "gin_server"
  username: "pengweiquan"
  password: "123123"
  config: "charset=utf8mb4&parseTime=True&loc=Local"